name: Release Drafter
on:
  push:
    branches:
      - main
jobs:
  publish_release:
    runs-on: small-runner
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
